### ISSUE TITLE
Not available on the Play Store or F-droid

### ISSUE THREAD

**Issue by calvarez-ov** [tasomaniac/DevWidget#9]
Hello!
I've built and installed this app and am quite pleased :)

Any chance it can be put back up on the Play Store and/or F-droid?

I'd like to recommend it to people who may not be motivated to build it themselves.

Thanks!

**Comment by tasomaniac** [comment]
Now available again in Play Store. Thanks for the report.

**Comment by tasomaniac** [comment]
For f-droid, I need to get back to it. Issue #1 is tracking that. It turned out to be not trivial.
